name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          git log --oneline | tac | nl | tac >> test.txt
          cat test.txt
          echo ugh
