name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        env:
          testing: ${{ secrets.test }}
        run: echo Hello, world! "$testing" > test.dat

      - name: Run a multi-line script
        run: |
          cat test.dat
          #echo test, and deploy your project.
