name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo artifact_days=5 >> ${{ github.env }}
      - name: Run a one-line script
        run: |
          mkdir test
          current=`date '+%Y-%m-%d-%H-%M-%S-%a'`;
          ls test
          touch "test/Built on $current"

      - name: test
        uses: actions/upload-artifact@v3
        with:
          path: test/*
          retention-days: {{ env.artifact_days }}
