name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          commit = `git rev-list HEAD --count`
          echo $commit
          chmod +x *.sh
          ./cl.sh

      - uses: actions/upload-artifact@v3
        with:
          path: cl.md
          retention-days: 1
