name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        env:
          testing: ${{ secrets.test }}
        run: |
          python test.py "$testing"
          echo test key - "$testing" > test.txt


      - name: test
        uses: actions/upload-artifact@v3
        with:
          path: test.txt
          if-no-files-found: error
          retention-days: 2
