name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: |
          mkdir test
          current=`date '+%Y-%m-%d-%H-%M-%S-%a'`;
          ls test
          touch test/$current

      - name: test
        uses: actions/upload-artifact@v3
        with:
          path: test/*
          retention-days: 1
