name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          test+=$'\n<details>'
          test+=$'\n<summary>Changelist</summary>'
          test+=$'\n\n'
          test+=$'```'
          test+=$'\n'$(git log --oneline)
          test+=$'\n```'
          test+=$'\n\n'
          test+='</details>'
          echo "$test" > test4.md
          echo test
          cat test4.md
